### ISSUE TITLE
invalid container.env

### ISSUE THREAD

**Issue by timolemke** [bodsch/ansible-container#24]
@bodsch thanks for your great work!
I have a problem, with the generated "container.env" file, which looks like

```
# generated by ansible
-Xmx1gSPRING_BOOT_EXPLODED_APP=true
```

and causes the JVM to fail at startup: Invalid maximum heap size: -Xmx1gSPRING_BOOT_EXPLODED_APP=true

The inventory looks like:
```
environments:
  JAVA_HEAP: 1g
  SPRING_BOOT_EXPLODED_APP: "true"
```

The porblem seems to be the non existent line break between the entries. Can you have a look? Thx!

**Comment by bodsch** [comment]
Hello @timolemke!

Can you please tell me which version of the Ansible role you are using?

**Comment by timolemke** [comment]
Hi @bodsch  I am using the latest version `2.4.0`

**Comment by bodsch** [comment]
Thanks

I still need the output of the following command line:

```
ansible-galaxy collection list | grep bodsch
```

**Comment by bodsch** [comment]
I have adapted the behaviour when creating the properties and environment files in version 2.4.1. however, this requires the new version of the collection [bodsch.core](https://galaxy.ansible.com/bodsch/core) !

Please update the collection **and** the role.

**Comment by timolemke** [comment]
Works with Version 2.4.2
Thx!
